import type { Metadata } from "next";
import "remixicon/fonts/remixicon.css";
import "./globals.css";
import ThemeProvider from "@/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import LayoutProvider from "@/providers/layout-providers";

export const metadata: Metadata = {
  title: "Givehub: A Hub for Giving",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="min-h-screen w-full bg-background text-foreground antialiased text-base p-4 sm:p-6 md:p-8 lg:p-10">
          <ThemeProvider>
            <LayoutProvider>{children}</LayoutProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
